# GET http://localhost:5000/shop/

# POST http://localhost:5000/shop/postCart
# Content-Type: application/json

# {
#     "productId": "676eb47a5cfa113abfe171d1"
# }

# GET http://localhost:5000/shop/products


#  POST http://localhost:5000/shop/postCart
#         Content-Type: application/json

#  { "productId": "676d11dda85fb3efc1f81598"}

# GET http://localhost:5000/shop/cart 
# Content-Type: application/json
# CSRF-Token: q4qGlZHx-MElQntC4K0vOKLm0D01s1eHR6_w


# POST http://localhost:5000/shop/createOrder 

# GET http://localhost:5000/shop/orders

# GET http://localhost:5000/csrf-token
# GET http://localhost:5000/status

# http://localhost:5000/shop/

# post http://localhost:5000/auth/signup
# Content-Type: application/json
# CSRF-Token: q4qGlZHx-MElQntC4K0vOKLm0D01s1eHR6_w

# {
#   "email": "anhsequayve922111gmail.com",
#   "password": "K12345",
#   "confirmPassword": "K12345"
# }

# post http://localhost:5000/auth/login
# Content-Type: application/json
# CSRF-Token: q4qGlZHx-MElQntC4K0vOKLm0D01s1eHR6_w

# {
#   "email": "",
#   "password": ""

# }

# post http://localhost:5000/shop/cartDeleteItem
# Content-Type: application/json
# CSRF-Token: 4b3BA0Hk-8DbRmNRZViyRF4ZbndU5EEbp_pM

# {
#   "productId": "67a8a30687549e9ff040dccd"

# }

# http://localhost:5000/admin/products
http://localhost:5000/images/



#  http://localhost:5000/auth/logout